name: tkdb_drift
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2

dependencies:
  drift: ^2.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  collection: ^1.17.0 # for firstWhereOrNull method
  console_bars: ^1.1.0

